Allowing compton on battery. Added obshutdown

diff --git a/.scripts/power/powerdown b/.scripts/power/powerdown
--- a/.scripts/power/powerdown
+++ b/.scripts/power/powerdown
@@ -112,10 +112,10 @@ opt /sys/module/snd_hda_intel/parameters/power_save_controller $SND_POWERSAVE_CO
 #opt /sys/module/snd_ac97_codec/parameters/power_save 1
 
 # composition, if present
-if [[ ! -z "`pidof compton`" ]]; then
-  echo "Compton running, trying to kill it.."
-  run kill -9 `pidof compton` &> /dev/null || echo "Error killing compton"
-fi
+#if [[ ! -z "`pidof compton`" ]]; then
+#  echo "Compton running, trying to kill it.."
+#  run kill -9 `pidof compton` &> /dev/null || echo "Error killing compton"
+#fi
 
 # brightness
 run light -S 2
